name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        go:
          - "stable"
          - "1.26"
          - "1.25"
          - "1.24"
          - "1.23"
          - "1.22"
          - "1.21"
    steps:
      - name: Check out the code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: go test -v -coverprofile=profile.cov ./...

      - name: Send coverage
        uses: shogo82148/actions-goveralls@9606dbc5ac5cf888a0e9ef901515c3cd516a2790 # v1.11.0
        with:
          path-to-profile: profile.cov
          parallel: true
          flag-name: OS-${{ runner.os }}-Go-${{ matrix.go }}

  # notifies that all test jobs are finished.
  finish:
    if: always()
    needs: test
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 1
    steps:
      - uses: shogo82148/actions-goveralls@9606dbc5ac5cf888a0e9ef901515c3cd516a2790 # v1.11.0
        with:
          parallel-finished: true
